![NYC Skyline](nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [97]:
# Import necessary packages
import pandas as pd
import numpy as np

# Begin coding here ...
# Use as many cells as you like

#Loading files
df_price = pd.read_csv('data/airbnb_price.csv')
df_room_type = pd.read_excel('data/airbnb_room_type.xlsx')
df_last_review = pd.read_csv('data/airbnb_last_review.tsv', sep='\t')

#looking loaded data frame
print(df_price.head())
print(df_room_type.head())
print(df_last_review.head())

   listing_id        price                nbhood_full
0        2595  225 dollars         Manhattan, Midtown
1        3831   89 dollars     Brooklyn, Clinton Hill
2        5099  200 dollars     Manhattan, Murray Hill
3        5178   79 dollars  Manhattan, Hell's Kitchen
4        5238  150 dollars       Manhattan, Chinatown
   listing_id                                description        room_type
0        2595                      Skylit Midtown Castle  Entire home/apt
1        3831            Cozy Entire Floor of Brownstone  Entire home/apt
2        5099  Large Cozy 1 BR Apartment In Midtown East  Entire home/apt
3        5178            Large Furnished Room Near B'way     private room
4        5238         Cute & Cozy Lower East Side 1 bdrm  Entire home/apt
   listing_id    host_name   last_review
0        2595     Jennifer   May 21 2019
1        3831  LisaRoxanne  July 05 2019
2        5099        Chris  June 22 2019
3        5178     Shunichi  June 24 2019
4        5238          Ben  June 09 2019

In [98]:
#merging all data frames
df_full_airbnb = pd.merge(df_price, df_room_type, on='listing_id', how='left')
df_full_airbnb = pd.merge(df_full_airbnb, df_last_review, on='listing_id', how='left')

df_full_airbnb.head()

   listing_id        price  ...    host_name   last_review
0        2595  225 dollars  ...     Jennifer   May 21 2019
1        3831   89 dollars  ...  LisaRoxanne  July 05 2019
2        5099  200 dollars  ...        Chris  June 22 2019
3        5178   79 dollars  ...     Shunichi  June 24 2019
4        5238  150 dollars  ...          Ben  June 09 2019

[5 rows x 7 columns]

In [99]:
#determining the earliest and most recent review dates
#Converting the column 'last_review' to datatime
df_full_airbnb['last_review'] = pd.to_datetime(df_full_airbnb['last_review'], infer_datetime_format=True)

earliest_review = min(df_full_airbnb['last_review'])
last_review = max(df_full_airbnb['last_review'])

print(earliest_review, last_review)

2019-01-01 00:00:00 2019-07-09 00:00:00

In [100]:
#Finding how many listings are private rooms

#cleaning the 'room_type' column
df_full_airbnb['room_type'] = df_full_airbnb['room_type'].str.lower()
print(df_full_airbnb['room_type'].unique())
#Subset private rooms and count

num_private_room = df_full_airbnb[df_full_airbnb['room_type'] == 'private room'].shape[0]

print(num_private_room)

['entire home/apt' 'private room' 'shared room']
11356

In [101]:
#Finding average price of listings
#Cleaning data

df_full_airbnb['price'] = df_full_airbnb['price'].str.replace('dollars', '')
print(df_full_airbnb.head())

#Converting string data to float data

df_full_airbnb['price'] = df_full_airbnb['price'].astype('float')

#Computing the mean price
mean_price = df_full_airbnb['price'].mean()
mean_price = round(mean_price, 2)
print(mean_price)

   listing_id price  ...    host_name last_review
0        2595  225   ...     Jennifer  2019-05-21
1        3831   89   ...  LisaRoxanne  2019-07-05
2        5099  200   ...        Chris  2019-06-22
3        5178   79   ...     Shunichi  2019-06-24
4        5238  150   ...          Ben  2019-06-09

[5 rows x 7 columns]
141.78

In [102]:
#Creating a data frame of review datas
dict_data ={
    'first_reviewed':[earliest_review],
    'last_reviewed':[last_review],
    'nb_private_rooms':[num_private_room],
    'avg_price':[mean_price]
}

review_dates = pd.DataFrame(dict_data)
print(review_dates)

  first_reviewed last_reviewed  nb_private_rooms  avg_price
0     2019-01-01    2019-07-09             11356     141.78